# Generated by Django 4.2.7 on 2024-05-26 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='services',
            name='available',
            field=models.BooleanField(default=True, verbose_name='Доступность услуги'),
        ),
    ]
